"""Public schema contracts shared across discovery, orchestration, registry, and fusion."""

from .capabilities import SensorCapabilityProfile, SensorType
from .models import (
    BoundingBox,
    Calibration,
    CameraInfo,
    Frame,
    FusionConfiguration,
    FusionRequest,
    FusionResponse,
    InferenceRequest,
    InferenceResponse,
    Mask,
    Mesh,
    ModelCapabilities,
    ModelRequirements,
    OutputSchema,
    PipelinePlan,
    PointCloud,
    Pose2D,
    Pose3D,
    RegistryDependency,
    RegistryResolution,
    SceneGraph,
    SceneObject,
    SceneRelationship,
    SourceDescriptor,
    Trajectory,
    WorkflowEdge,
    WorkflowGraph,
    WorkflowNode,
)

__all__ = [
    "BoundingBox",
    "Calibration",
    "CameraInfo",
    "Frame",
    "FusionConfiguration",
    "FusionRequest",
    "FusionResponse",
    "InferenceRequest",
    "InferenceResponse",
    "Mask",
    "Mesh",
    "ModelCapabilities",
    "ModelRequirements",
    "OutputSchema",
    "PipelinePlan",
    "PointCloud",
    "Pose2D",
    "Pose3D",
    "RegistryDependency",
    "RegistryResolution",
    "SceneGraph",
    "SceneObject",
    "SceneRelationship",
    "SensorCapabilityProfile",
    "SensorType",
    "SourceDescriptor",
    "Trajectory",
    "WorkflowEdge",
    "WorkflowGraph",
    "WorkflowNode",
]
