name: Build

on:
  push:
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -f docker/Dockerfile -t universal-cv-adapter:ci .
